// A comprehensive list of all Toronto Public Library branch names.
export const tplLocations = [
  "TPL Agincourt",
  "TPL Albert Campbell",
  "TPL Albion",
  "TPL Alderwood",
  "TPL Amesbury Park",
  "TPL Annette Street",
  "TPL Armour Heights",
  "TPL Barbara Frum",
  "TPL Beaches",
  "TPL Bendale",
  "TPL Black Creek",
  "TPL Bloor/Gladstone",
  "TPL Brentwood",
  "TPL Bridlewood",
  "TPL Brookbanks",
  "TPL Burrows Hall",
  "TPL Cedarbrae",
  "TPL Centennial",
  "TPL City Hall",
  "TPL Cliffcrest",
  "TPL College/Shaw",
  "TPL Danforth/Coxwell",
  "TPL Davenport",
  "TPL Dawes Road",
  "TPL Deer Park",
  "TPL Don Mills",
  "TPL Downsview",
  "TPL Dufferin/St. Clair",
  "TPL Eatonville",
  "TPL Eglinton Square",
  "TPL Elmbrook Park",
  "TPL Ethennonnhawahstihnen'",
  "TPL Evelyn Gregory",
  "TPL Fairview",
  "TPL Flemingdon Park",
  "TPL Forest Hill",
  "TPL Fort York",
  "TPL Gerrard/Ashdale",
  "TPL Goldhawk Park",
  "TPL Guildwood",
  "TPL High Park",
  "TPL Highland Creek",
  "TPL Hillcrest",
  "TPL Humber Bay",
  "TPL Humber Summit",
  "TPL Humberwood",
  "TPL Jane/Dundas",
  "TPL Jane/Sheppard",
  "TPL Jones",
  "TPL Kennedy/Eglinton",
  "TPL Leaside",
  "TPL Lillian H. Smith",
  "TPL Locke",
  "TPL Long Branch",
  "TPL Malvern",
  "TPL Maria A. Shchuka",
  "TPL Maryvale",
  "TPL McGregor Park",
  "TPL Merril Collection of Science Fiction",
  "TPL Mimico Centennial",
  "TPL Morningside",
  "TPL Mount Dennis",
  "TPL Mount Pleasant",
  "TPL New Toronto",
  "TPL North York Central Library",
  "TPL Northern District",
  "TPL Oakwood Village",
  "TPL Palmerston",
  "TPL Pape/Danforth",
  "TPL Parkdale",
  "TPL Parliament Street",
  "TPL Perth/Dupont",
  "TPL Pleasant View",
  "TPL Port Union",
  "TPL Queen/Saulter",
  "TPL Regina Mundi",
  "TPL Rexdale",
  "TPL Richview",
  "TPL Riverdale",
  "TPL Runnymede",
  "TPL S. Walter Stewart",
  "TPL Sanderson",
  "TPL Scarborough Civic Centre",
  "TPL Spadina Road",
  "TPL St. Clair/Silverthorn",
  "TPL St. James Town",
  "TPL St. Lawrence",
  "TPL Steeles",
  "TPL Swansea Memorial",
  "TPL Taylor Memorial",
  "TPL Thorncliffe",
  "TPL Todmorden Room",
  "TPL Toronto Reference Library",
  "TPL Victoria Village",
  "TPL Weston",
  "TPL Woodbridge",
  "TPL Woodside Square",
  "TPL Wychwood",
  "TPL York Woods",
  "TPL Yorkville"
];
